### ISSUE TITLE
Использовать поле hstore

### ISSUE THREAD

**Issue by nextstopsun** [Scondo/fiosm#13]
Можно ли вместо ряда полей, в которые раскладываются нужные теги осма, использовать одно поле tags типа hstore?

**Comment by nextstopsun** [comment]
@Scondo ping 😄

**Comment by Scondo** [comment]
Ну, это штатная возможность osm2pgsql.

Я пробовал - получилось не очень эффективно: усложняется код, усложняется формулировка индеков. А преимуществ особенных не получилось.
